"""create initial tables

Revision ID: 0c78f545f760
Revises: 
Create Date: 2026-09-23 15:24:46.185977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c78f545f760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('overseer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['overseer_id'], ['users.id'], name='fk_group_overseer', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('overseer_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('date_of_baptism', sa.Date(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_users_group', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reporting_month', sa.Date(), nullable=False),
    sa.Column('service_type', sa.Enum('publisher', 'auxiliary_pioneer', 'regular_pioneer', name='servicetype'), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('bible_studies', sa.Integer(), nullable=False),
    sa.Column('participated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'in_review', 'approved', 'returned', name='status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('original_submission_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reporting_month', name='uq_user_reporting_month')
    )
    op.create_table('service_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('publisher', 'auxiliary_pioneer', 'regular_pioneer', name='servicetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('publisher', 'group_overseer', 'secretary', 'elder', 'admin', 'service_overseer', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('service_assignments')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
